apiVersion: v1
kind: Service
metadata: 
  name: drupal-db
spec: 
  ports: 
    - name: mariadb
      port: 3306
      protocol: TCP
  selector: 
    app: drupal-db

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: drupal-db
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: drupal-db
  template: 
    metadata: 
      labels: 
        app: drupal-db
    spec: 
      containers: 
        - name: cont-drupal-db
          env: 
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-auth
                key: password
          - name: MARIADB_DATABASE
            value: drupal-database
          image: mariadb
          ports: 
            - containerPort: 3306
              name: db-port
          volumeMounts: 
            - mountPath: /var/lib/mysql
              name: vol-db
          readinessProbe:
            tcpSocket:
              port: db-port
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: db-port
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes: 
        - name: vol-db
          persistentVolumeClaim: 
            claimName: drupal-pvc-db