apiVersion: v1
kind: Service
metadata: 
  name: drupal
spec: 
  ports: 
    - name: http
      port: 80
      protocol: TCP
  selector: 
    app: drupal

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: drupal
  name: drupal
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template: 
    metadata: 
      labels: 
        app: drupal
    spec: 
      initContainers:
        - name: init-sites-volume
          image: drupal:8.6
          command: ['/bin/bash', '-c']
          args: ['cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R']
          volumeMounts:
          - mountPath: /data
            name: vol-drupal
      containers: 
        - name: drupal
          image: drupal:8.6
          ports: 
            - containerPort: 80
          volumeMounts:
          - mountPath: /var/www/html/modules
            name: vol-drupal
            subPath: modules
          - mountPath: /var/www/html/profiles
            name: vol-drupal
            subPath: profiles
          - mountPath: /var/www/html/sites
            name: vol-drupal
            subPath: sites
          - mountPath: /var/www/html/themes
            name: vol-drupal
            subPath: themes
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            failureThreshold: 5
            timeoutSeconds: 40
            periodSeconds: 30
      volumes:
        - name: vol-drupal
          persistentVolumeClaim: 
            claimName: drupal-pvc
