apiVersion: v1
kind: Service
metadata: 
  name: drupal-db
spec: 
  ports: 
    - name: postgres
      port: 5432
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: drupal-db
spec:
  template:
    spec:
      containers:
        - name: cont-drupal-db
          env: 
          - name: POSTGRES_USER
            value: root
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-auth
                key: password
          - name: POSTGRES_DB
            value: drupal-database