apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

images:
- name: mariadb
  newName: postgres
  newTag: "10.4"

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: drupal-db
    namespace: default
  path: db-edit.yaml

patchesStrategicMerge:
- db.yaml